# 1) Build aşaması
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Projeyi kopyala ve restore et
COPY *.sln .
COPY JiraProject.WebAPI/*.csproj JiraProject.WebAPI/
COPY JiraProject.Business/*.csproj JiraProject.Business/
COPY JiraProject.DataAccess/*.csproj JiraProject.DataAccess/
COPY JiraProject.Entities/*.csproj JiraProject.Entities/
RUN dotnet restore

# Tüm solution’u kopyala ve publish et
COPY . .
WORKDIR /src/JiraProject.WebAPI
RUN dotnet publish -c Release -o /app/publish

# 2) Runtime aşaması
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "JiraProject.WebAPI.dll"]
